version: '3.9'
services:
  backend:
    container_name: backend
    build: ./backend
    ports: 
      - 5080:5080
    networks:
      - test_task_net
    env_file:
      - ./backend/env.env
    depends_on:
      - rabbitmq
    restart: on-failure
  frontend:
    container_name: frontend
    build: ./frontend
    ports: 
      - 8080:80
    networks:
      - test_task_net
  rabbitmq:
    container_name: rabbitmq
    build: ./rabbitmq
    ports: 
      - 15672:15672
    networks:
      - test_task_net
  db:
    container_name: db
    build: ./db
    ports: 
      - 15432:5432
    networks:
      - test_task_net
    env_file:
      - ./db/env.env
    volumes:
      - './db/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf'
  migration:
    container_name: migration
    build: ./servicedb
    networks:
      - test_task_net
    env_file:
      - ./servicedb/env.env
    command: alembic upgrade head
    depends_on:
      - db
    restart: on-failure
  servicesdb:
    container_name: servicedb
    build: ./servicedb
    networks:
      - test_task_net
    env_file:
      - ./servicedb/env.env
    depends_on:
      - migration
      - rabbitmq
    restart: on-failure
networks:
  test_task_net: 
    name: test_task_net